language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - curl -sS https://getcomposer.org/installer | php

install:
  - php composer.phar install

notifications:
  email:
    - bliequearts@gmail.com
